# Generated by Django 4.0.3 on 2023-04-29 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custname', models.CharField(max_length=350)),
                ('custnumb', models.IntegerField(blank=True, null=True)),
                ('itemname', models.CharField(blank=True, max_length=350, null=True)),
                ('itemprice', models.FloatField(default=0)),
                ('itemquntity', models.FloatField(default=0)),
                ('itemtotal', models.FloatField(default=0)),
                ('itemcode', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=350, null=True)),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default=1, max_length=2)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tempitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempname', models.CharField(blank=True, max_length=350, null=True)),
                ('tempprice', models.FloatField(default=0)),
                ('tempquntity', models.FloatField(default=0)),
                ('temptotal', models.FloatField(default=0)),
            ],
        ),
    ]
