# Generated by Django 4.0.3 on 2023-04-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbill',
            name='itemcode',
            field=models.CharField(max_length=50),
        ),
    ]
