# Generated by Django 4.0.3 on 2023-04-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invApp', '0002_alter_customerbill_itemcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoiceitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(blank=True, max_length=350, null=True)),
                ('itemprice', models.FloatField(default=0)),
                ('itemquntity', models.FloatField(default=0)),
                ('itemtotal', models.FloatField(default=0)),
                ('itemcode', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='customerbill',
            name='itemname',
        ),
        migrations.RemoveField(
            model_name='customerbill',
            name='itemprice',
        ),
        migrations.RemoveField(
            model_name='customerbill',
            name='itemquntity',
        ),
        migrations.RemoveField(
            model_name='customerbill',
            name='itemtotal',
        ),
        migrations.AddField(
            model_name='customerbill',
            name='totalitem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='totalprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerbill',
            name='custnumb',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
