# Generated by Django 4.0.3 on 2023-05-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invApp', '0004_alter_invoiceitem_itemquntity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='totalquantity',
            field=models.IntegerField(default=0),
        ),
    ]
