# Generated by Django 4.1.6 on 2023-05-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invApp', '0005_product_totalquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=12, max_length=350),
            preserve_default=False,
        ),
    ]
