# Generated by Django 4.0.3 on 2023-05-09 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invApp', '0006_alter_product_description_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
