# Generated by Django 4.0.3 on 2023-05-09 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invApp', '0007_customerbill_date_created_invoiceitem_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(blank=True, max_length=350, null=True)),
                ('itemquntity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('1', 'Stock in'), ('2', 'Stock out')], default=1, max_length=2)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
