# Generated by Django 4.0.3 on 2023-05-10 07:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invApp', '0011_alter_customerbill_id_alter_invoiceitem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbill',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
