# Generated by Django 4.0.3 on 2023-05-10 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invApp', '0014_customerbill_cust_id_alter_customerbill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbill',
            name='cust_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
