# Generated by Django 4.0.3 on 2023-05-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invApp', '0016_remove_customerbill_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbill',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tempitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
