# Generated by Django 4.1.6 on 2023-05-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invApp', '0019_product_size_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='itemsize',
            field=models.CharField(default='10mm', max_length=50),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='itemsize',
            field=models.CharField(default='10mm', max_length=50),
        ),
        migrations.AddField(
            model_name='tempitem',
            name='tempsize',
            field=models.CharField(default='10mm', max_length=50),
        ),
    ]
